#!/bin/bash

# Default AWS profile if not provided
DEFAULT_PROFILE="default"

# List of colors for text
RESET='\033[0m'
RED='\033[0;31m' 
GREEN='\033[0;32m'
BLUE='\033[0;34m' 
CYAN='\033[0;36m' 
 
# Clear terminal
clear 

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set the base directory (project root) - one level up from scripts directory
BASE_DIR="$( cd "${SCRIPT_DIR}/.." && pwd )"

# Set paths relative to the base directory
TERRAFORM_DIR="${BASE_DIR}/backend/terraform"
FRONTEND_DIR="${BASE_DIR}/frontend"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --profile)
      AWS_PROFILE="$2"
      shift 2
      ;;
    --help)
      echo "Usage: $0 [--profile PROFILE_NAME]"
      echo "  --profile PROFILE_NAME  AWS profile to use (default: $DEFAULT_PROFILE)"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

# Set the working directory to the backend/terraform directory
cd "${TERRAFORM_DIR}"

# Run terraform refresh to ensure state is up to date
echo -e "${BLUE}Refreshing Terraform state...${RESET}"
terraform refresh > /dev/null
echo ""

# Now capture the aws_profile output
terraform_aws_profile=$(terraform output -raw aws_profile 2>/dev/null || echo "")
echo "=========================================="
echo -e "Terraform aws_profile: ${CYAN}$terraform_aws_profile${RESET}"

# Set AWS profile with priority: command line > terraform output > default
AWS_PROFILE=${AWS_PROFILE:-${terraform_aws_profile:-$DEFAULT_PROFILE}}
echo -e "Using AWS profile: ${CYAN} $AWS_PROFILE ${RESET}"
echo "=========================================="
echo ""
# Capture Terraform Outputs
echo -e "${BLUE}Capturing Terraform Outputs...${RESET}"

api_endpoint=$(terraform output -raw api_endpoint 2>/dev/null || echo "")
cognito_user_pool_id=$(terraform output -raw cognito_user_pool_id 2>/dev/null || echo "")
cognito_user_pool_client_id=$(terraform output -raw cognito_user_pool_client_id 2>/dev/null || echo "")
cognito_identity_pool_id=$(terraform output -raw cognito_identity_pool_id 2>/dev/null || echo "")
aws_region=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")
storage_bucket_name=$(terraform output -raw storage_bucket_name 2>/dev/null || echo "")
frontend_bucket_name=$(terraform output -raw frontend_bucket_name 2>/dev/null || echo "meeting-audio-summarizer-frontend")
cloudfront_distribution_domain=$(terraform output -raw cloudfront_distribution_domain 2>/dev/null || echo "")
cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id 2>/dev/null || echo "")
state_machine_arn=$(terraform output -raw state_machine_arn 2>/dev/null || echo "")

echo ""
# Display captured outputs
echo -e "${BLUE}Displaying Captured Outputs...${RESET}"
echo "========================================================================================="
echo -e  "api_endpoint                         = ${GREEN}\"$api_endpoint\"${RESET}"
echo -e  "cloudfront_distribution_domain       = ${GREEN}\"$cloudfront_distribution_domain\"${RESET}"
echo -e  "cognito_identity_pool_id             = ${GREEN}\"$cognito_identity_pool_id\"${RESET}"
echo -e  "cognito_user_pool_client_id          = ${GREEN}\"$cognito_user_pool_client_id\"${RESET}"
echo -e  "cognito_user_pool_id                 = ${GREEN}\"$cognito_user_pool_id\"${RESET}"
echo -e  "state_machine_arn                    = ${GREEN}\"$state_machine_arn\"${RESET}"
echo -e  "storage_bucket_name                  = ${GREEN}\"$storage_bucket_name\"${RESET}"
echo -e  "aws_region                           = ${GREEN}\"$aws_region\"${RESET}"
echo -e  "frontend_bucket_name                 = ${GREEN}\"$frontend_bucket_name\"${RESET}"
echo -e  "cloudfront_distribution_id           = ${GREEN}\"$cloudfront_distribution_id\"${RESET}"
echo "========================================================================================="
echo ""

# Navigate to the frontend directory
cd "${FRONTEND_DIR}"

# Update Frontend Configuration
echo -e "${BLUE}Updating Frontend Configuration...${RESET}"      
cat > src/aws-exports.js << EOL
/* eslint-disable */
// WARNING: This file is automatically generated based on Terraform outputs
// Last updated: $(date)

const awsmobile = {
  "aws_project_region": "$aws_region",
  "aws_appsync_graphqlEndpoint": "$api_endpoint",
  "aws_appsync_region": "$aws_region",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_cognito_identity_pool_id": "$cognito_identity_pool_id",
  "aws_cognito_region": "$aws_region",
  "aws_user_pools_id": "$cognito_user_pool_id",
  "aws_user_pools_web_client_id": "$cognito_user_pool_client_id",
  "aws_user_files_s3_bucket": "$storage_bucket_name",
  "aws_user_files_s3_bucket_region": "$aws_region",
  "aws_cloudfront_domain": "$cloudfront_distribution_domain"
};
export default awsmobile;
EOL
echo ""
echo -e "${BLUE}Frontend configuration updated with backend resources...${RESET}"      

# Build the frontend
echo ""
echo -e "${BLUE}Building Frontend...${RESET}"
npm run build
echo ""

# Deploy to S3
echo -e "${BLUE}Deploying Frontend...${RESET}"      
echo ""

aws s3 sync build/ s3://$frontend_bucket_name --delete --profile $AWS_PROFILE

# Invalidate CloudFront cache
echo ""
echo -e "${BLUE}Invalidating CloudFront Cache...${RESET}"
if [ -n "$cloudfront_distribution_id" ]; then
  # Use --no-paginate and redirect output to a file to prevent interactive pager
  aws cloudfront create-invalidation --distribution-id $cloudfront_distribution_id --paths "/*" --profile $AWS_PROFILE --no-paginate --output json > /tmp/cf_invalidation.json
  echo ""
  echo -e "✅ ${GREEN}CloudFront invalidation created successfully${RESET}"
  # Optionally display the invalidation ID
  INVALIDATION_ID=$(cat /tmp/cf_invalidation.json | grep -o '"Id": "[^"]*"' | cut -d'"' -f4)
  echo ""
  echo -e "Invalidation ID: ${GREEN}$INVALIDATION_ID${RESET}"
else
  echo "Warning: CloudFront distribution ID not found in Terraform outputs. Skipping invalidation."
fi
echo ""
echo ""
echo -e "${GREEN}Deployment complete! :)${RESET}"
echo ""
if [ -n "$cloudfront_distribution_domain" ]; then
  echo "----------------------------------------------------------------------------------------------"
  echo -e "${YELLOW} Your app is available at: ${RESET}${BLUE} https://$cloudfront_distribution_domain ${RESET}"
  echo "----------------------------------------------------------------------------------------------"
else
  echo -e "❌ ${RED}CloudFront domain not found. Check your Terraform outputs."
fi
